version: 2

models:
  - name: int_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: int_accounts
    columns:
      - name: account_id
        tests: [not_null, unique]
      - name: account_sub_type
      - name: plan_tier

  - name: int_transactions
    columns:
      - name: transaction_id
        tests: [not_null, unique]

  - name: int_transactions_enriched
    columns:
      - name: transaction_id
        tests: [not_null, unique]

  - name: int_daily_finance_metrics
    columns:
      - name: transaction_date
        tests: [not_null]
      - name: currency
        tests: [not_null]

  - name: int_customer_kyc_status
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: latest_kyc_application_id
        tests: [not_null]
